FROM daocloud.io/nginx:1.9.14
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#ADD /webui/webui.tar.gz /usr/share/nginx/html
ADD /code/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /etc/nginx/conf.d/cert
ADD /code/214090251070401.key /etc/nginx/conf.d/cert/214090251070401.key
ADD /code/214090251070401.pem /etc/nginx/conf.d/cert/214090251070401.pem
COPY /code/setVersion.sh /
#RUN cd /usr/share/nginx/html && mv dist webui
RUN chmod 777 /setVersion.sh