server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      enabled: true
      server:
#        git:
#          uri: https://git.coding.net/tdcarefor/config-repo.git
#          searchPaths: tdcloud
#          username: tdcarefor
#          password: Tdkk123
#          basedir: target/config
        native:
          searchLocations: classpath:config/

