server:
  port: 8086
  session:
   # store-dir: /data/session
    timeout: 604800
    cookie:
      name: APIGateWayJSESSIONID
     # max-age: 604800  #7*24*60*60 一个星期后重新登录
spring:
  aop:
    proxyTargetClass: true


zuul:
  routes:
    user:
      path: /user/**
      serviceId: user

    open:
      path: /open/**
      serviceId: open

    uaa:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
#    ui:
#      path: /ui/**
#      url: http://localhost:8989/
  add-proxy-headers: true

security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 15000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000