endpoints:
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/

spring:
#  rabbitmq:
#      host: 114.55.73.49
#      username: guest
#      password: guest
  cloud:
    #用环境变量覆盖远程参数
      config:
        allowOverride: true
        overrideSystemProperties: false
#对外服务IP和端口
proxy:
  ip: localhost:8086


# Disable spring basic authentication security
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
      loadBalanced: true
    client:
      accessTokenUri: http://${proxy.ip}/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: tdcloud
      clientSecret: acmesecret
      access-token-validity-seconds: 31104000 #access-token 过期时间为1年，防止微服务之间调用过期。

feign:
  hystrix:
    enabled: true
hystrix.command.default.execution.isolation.strategy: SEMAPHORE

springfox:
  documentation:
    swagger:
      v2:
        host: ${proxy.ip}

api:
  version: 1.0.0
#每个微服务，quartz的表名不一样,为微服务的名字加"_"
quartz.tablePrefix: ${spring.application.name}_
#每个微服务的数据库版本记录名为,为微服务的名字加"_version"
flyway.table: ${spring.application.name}_version
flyway.baseline-on-migrate: true
flyway.ignore-failed-future-migration: true

logging:
  level.org.springframework.security: DEBUG
#  level.root: ERROR
  level.com.atomikos: ERROR
  level.me.tdcarefor: TRACE
 # level.org.axonframework: DEBUG





