# Define the port where the UAA server would be running
server:
  port: 8015
  session:
    #store-dir: /data/session
    timeout: 604800
    cookie:
      name: UAAJSESSIONID
      max-age: 604800  #7*24*60*60 一个星期后重新登录
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: true
  tomcat:
      remote_ip_header: x-forwarded-for


security:
  basic:
    enabled: false
  ignored: /css/**,/js/**,/images/**,/favicon.ico,/webjars/**

#logging:
#  level.org.springframework.security: DEBUG
#  level.com.atomikos: ERROR

springfox:
  documentation:
    swagger:
      v2:
        host: ${proxy.ip}


